name: bayes_course

channels:
  - conda-forge
dependencies:
  - python
  - ipython
  - ipywidgets
  - jax
  - jaxlib
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - numpyro
  - pandas
  - patsy
  - pip
  - polars
  - pymc
  - pydot
  - python-graphviz
  - scipy
  - seaborn
  - setuptools
